# Generated by Django 5.1 on YYYY-MM-DD HH:MM

from django.db import migrations, models


def transfer_profile_data(apps, schema_editor):
    OldProfile = apps.get_model("oc_lettings_site", "Profile")
    NewProfile = apps.get_model("profiles", "Profile")
    User = apps.get_model("auth", "User")

    for old_profile in OldProfile.objects.all():
        user = User.objects.get(pk=old_profile.user_id)
        NewProfile.objects.create(
            user=user,
            favorite_city=old_profile.favorite_city,  # Transférer les autres champs si nécessaire
        )


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiles",
            "0001_initial",
        ),  # Assurez-vous que c'est la dernière migration créée pour profiles
        (
            "oc_lettings_site",
            "0001_initial",
        ),  # Assurez-vous que c'est la dernière migration créée pour oc_lettings_site
    ]

    operations = [
        migrations.RunPython(transfer_profile_data),
    ]
