# Generated by Django 5.1 on 2024-09-09 13:34

from django.db import migrations


def transfer_data(apps, schema_editor):
    OldAddress = apps.get_model("oc_lettings_site", "Address")
    OldLetting = apps.get_model("oc_lettings_site", "Letting")
    OldProfile = apps.get_model("oc_lettings_site", "Profile")

    NewAddress = apps.get_model("lettings", "Address")
    NewLetting = apps.get_model("lettings", "Letting")
    NewProfile = apps.get_model("profiles", "Profile")

    old_addresses = OldAddress.objects.all()
    for old_address in old_addresses:
        new_address = NewAddress.objects.create(
            number=old_address.number,
            street=old_address.street,
            city=old_address.city,
            state=old_address.state,
            zip_code=old_address.zip_code,
            country_iso_code=old_address.country_iso_code,
        )
        old_lettings = OldLetting.objects.filter(address=old_address)
        for old_letting in old_lettings:
            NewLetting.objects.create(title=old_letting.title, address=new_address)
    old_profiles = OldProfile.objects.all()
    for old_profile in old_profiles:
        NewProfile.objects.create(
            user=old_profile.user, favorite_city=old_profile.favorite_city
        )


class Migration(migrations.Migration):

    dependencies = [
        ("oc_lettings_site", "0001_initial"),
        ("profiles", "0001_initial"),
        ("lettings", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(transfer_data),
    ]
