# Generated by Django 5.1 on 2024-09-09 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oc_lettings_site", "0003_auto_20240909_1303"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OldAddress",
        ),
        migrations.DeleteModel(
            name="OldLetting",
        ),
        migrations.DeleteModel(
            name="OldProfile",
        ),
    ]
